(function(){'use strict';var f,aa=typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if(typeof Object.setPrototypeOf=="function")g=Object.setPrototypeOf;else{var k;a:{var ba={a:!0},ca={};try{ca.__proto__=ba;k=ca.a;break a}catch(a){}k=!1}g=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var da=g,n=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(da)da(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.tc=b.prototype},ea=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},fa=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ea(a)};
throw Error(String(a)+" is not an iterable or ArrayLike");};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var q=this||self,r=function(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"},u="closure_uid_"+(Math.random()*1E9>>>0),ha=0,ia=function(a,b,c){return a.call.apply(a.bind,arguments)},ja=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,
arguments)}},v=function(a,b,c){v=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ia:ja;return v.apply(null,arguments)},w=function(a,b){a=a.split(".");for(var c=q,d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};var chrome=chrome||window.chrome||{};chrome.cast=chrome.cast||{};chrome.cast.media=chrome.cast.media||{};chrome.cast.ReceiverActionListener={};chrome.cast.VERSION=[1,2];w("chrome.cast.VERSION",chrome.cast.VERSION);chrome.cast.sc=!0;w("chrome.cast.usingPresentationApi",chrome.cast.sc);chrome.cast.Oa=function(a,b){this.credentials=a;this.credentialsType=b===void 0?"web":b};w("chrome.cast.CredentialsData",chrome.cast.Oa);chrome.cast.Error=function(a,b,c){this.code=a;this.description=b||null;this.details=c||null};w("chrome.cast.Error",chrome.cast.Error);
chrome.cast.ob=function(a){this.platform=a;this.packageId=this.url=null};w("chrome.cast.SenderApplication",chrome.cast.ob);chrome.cast.Image=function(a){this.url=a;this.width=this.height=null};w("chrome.cast.Image",chrome.cast.Image);chrome.cast.Volume=function(a,b){this.level=a===void 0?null:a;this.muted=b===void 0?null:b};w("chrome.cast.Volume",chrome.cast.Volume);chrome.cast.ia={CUSTOM_CONTROLLER_SCOPED:"custom_controller_scoped",TAB_AND_ORIGIN_SCOPED:"tab_and_origin_scoped",ORIGIN_SCOPED:"origin_scoped",PAGE_SCOPED:"page_scoped"};w("chrome.cast.AutoJoinPolicy",chrome.cast.ia);chrome.cast.ka={CREATE_SESSION:"create_session",CAST_THIS_TAB:"cast_this_tab"};w("chrome.cast.DefaultActionPolicy",chrome.cast.ka);chrome.cast.Na={VIDEO_OUT:"video_out",AUDIO_OUT:"audio_out",VIDEO_IN:"video_in",AUDIO_IN:"audio_in",MULTIZONE_GROUP:"multizone_group"};
w("chrome.cast.Capability",chrome.cast.Na);chrome.cast.B={CANCEL:"cancel",TIMEOUT:"timeout",API_NOT_INITIALIZED:"api_not_initialized",INVALID_PARAMETER:"invalid_parameter",EXTENSION_NOT_COMPATIBLE:"extension_not_compatible",EXTENSION_MISSING:"extension_missing",RECEIVER_UNAVAILABLE:"receiver_unavailable",SESSION_ERROR:"session_error",CHANNEL_ERROR:"channel_error",LOAD_MEDIA_FAILED:"load_media_failed"};w("chrome.cast.ErrorCode",chrome.cast.B);chrome.cast.O={AVAILABLE:"available",UNAVAILABLE:"unavailable"};
w("chrome.cast.ReceiverAvailability",chrome.cast.O);chrome.cast.pb={CHROME:"chrome",IOS:"ios",ANDROID:"android"};w("chrome.cast.SenderPlatform",chrome.cast.pb);chrome.cast.ya={CAST:"cast",DIAL:"dial",HANGOUT:"hangout",CUSTOM:"custom"};w("chrome.cast.ReceiverType",chrome.cast.ya);chrome.cast.Qa={RUNNING:"running",STOPPED:"stopped",ERROR:"error"};w("chrome.cast.DialAppState",chrome.cast.Qa);chrome.cast.kb={CAST:"cast",STOP:"stop"};w("chrome.cast.ReceiverAction",chrome.cast.kb);
chrome.cast.L={CONNECTED:"connected",DISCONNECTED:"disconnected",STOPPED:"stopped"};w("chrome.cast.SessionStatus",chrome.cast.L);chrome.cast.Eb={ATTENUATION:"attenuation",FIXED:"fixed",MASTER:"master"};w("chrome.cast.VolumeControlType",chrome.cast.Eb);var ka=/&/g,la=/</g,ma=/>/g,na=/"/g,oa=/'/g,pa=/\x00/g,qa=/[\x00&<>"']/;/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var ra={};function sa(){if(ra!==ra)throw Error("Bad secret");};var ta=globalThis.trustedTypes,x;function ua(){var a=null;if(!ta)return a;try{var b=function(c){return c};a=ta.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){throw c;}return a};var y=function(a){sa();this.h=a};y.prototype.toString=function(){return this.h};new y("about:blank");new y("about:invalid#zClosurez");var va=[],wa=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};va.indexOf(wa)===-1&&va.push(wa);var z=function(a){sa();this.h=a};z.prototype.toString=function(){return this.h+""};var xa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function ya(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return e;return-1};var za=Object.freeze||function(a){return a};var Ba=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=q.document.createElement("div");return a.replace(Aa,function(d,e){var h=b[d];if(h)return h;e.charAt(0)=="#"&&(e=Number("0"+e.slice(1)),isNaN(e)||(h=String.fromCharCode(e)));if(!h){h=d+" ";x===void 0&&(x=ua());h=(e=x)?e.createHTML(h):h;h=new z(h);if(c.nodeType===1&&(e=c.tagName,/^(script|style)$/i.test(e)))throw d=e.toLowerCase()==="script"?"Use setScriptTextContent with a SafeScript.":"Use setStyleTextContent with a SafeStyleSheet.",
Error(d);if(h instanceof z)h=h.h;else throw Error("Unexpected type when unwrapping SafeHtml");c.innerHTML=h;h=c.firstChild.nodeValue.slice(0,-1)}return b[d]=h})},Ca=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:return c.charAt(0)!="#"||(c=Number("0"+c.slice(1)),isNaN(c))?b:String.fromCharCode(c)}})},Aa=/&([^;\s<&]+);?/g;chrome.cast.Ja=function(a,b,c,d,e){this.sessionRequest=a;this.sessionListener=b;this.receiverListener=c;this.autoJoinPolicy=d||chrome.cast.ia.TAB_AND_ORIGIN_SCOPED;this.defaultActionPolicy=e||chrome.cast.ka.CREATE_SESSION;this.customDialLaunchCallback=null;this.invisibleSender=!1;this.additionalSessionRequests=[]};w("chrome.cast.ApiConfig",chrome.cast.Ja);chrome.cast.Ta=function(a,b){this.appName=a;this.launchParameter=b||null};w("chrome.cast.DialRequest",chrome.cast.Ta);
chrome.cast.Ra=function(a,b,c){this.receiver=a;this.appState=b;this.extraData=c||null};w("chrome.cast.DialLaunchData",chrome.cast.Ra);chrome.cast.Sa=function(a,b){this.doLaunch=a;this.launchParameter=b||null};w("chrome.cast.DialLaunchResponse",chrome.cast.Sa);
chrome.cast.qb=function(a,b,c,d,e){c=c===void 0?chrome.cast.timeout.requestSession:c;this.appId=a;this.capabilities=Array.isArray(b)?b:[];this.requestSessionTimeout=c;this.dialRequest=this.language=null;this.androidReceiverCompatible=d===void 0?!1:d;this.credentialsData=e===void 0?null:e};w("chrome.cast.SessionRequest",chrome.cast.qb);
chrome.cast.jb=function(a,b,c,d){this.label=a;a=b;qa.test(a)&&(a.indexOf("&")!=-1&&(a=a.replace(ka,"&amp;")),a.indexOf("<")!=-1&&(a=a.replace(la,"&lt;")),a.indexOf(">")!=-1&&(a=a.replace(ma,"&gt;")),a.indexOf('"')!=-1&&(a=a.replace(na,"&quot;")),a.indexOf("'")!=-1&&(a=a.replace(oa,"&#39;")),a.indexOf("\x00")!=-1&&(a=a.replace(pa,"&#0;")));this.friendlyName=a;this.capabilities=c||[];this.volume=d||null;this.receiverType=chrome.cast.ya.CAST;this.displayStatus=this.isActiveInput=null};
w("chrome.cast.Receiver",chrome.cast.jb);chrome.cast.lb=function(a,b){this.statusText=a;this.appImages=b;this.showStop=null};w("chrome.cast.ReceiverDisplayStatus",chrome.cast.lb);chrome.cast.Ba=function(){this.requestSession=6E4;this.getDialAppInfo=this.sendCustomMessage=this.setReceiverVolume=this.stopSession=this.leaveSession=3E3};w("chrome.cast.Timeout",chrome.cast.Ba);chrome.cast.timeout=new chrome.cast.Ba;w("chrome.cast.timeout",chrome.cast.timeout);chrome.cast.Ia="auto-join";
chrome.cast.eb="cast-session_";chrome.cast.media.Wa={SDR:"sdr",HDR:"hdr",DV:"dv"};w("chrome.cast.media.HdrType",chrome.cast.media.Wa);chrome.cast.media.Xa={AAC:"aac",AC3:"ac3",MP3:"mp3",TS:"ts",TS_AAC:"ts_aac",E_AC3:"e_ac3",FMP4:"fmp4"};w("chrome.cast.media.HlsSegmentFormat",chrome.cast.media.Xa);chrome.cast.media.Ya={MPEG2_TS:"mpeg2_ts",FMP4:"fmp4"};w("chrome.cast.media.HlsVideoSegmentFormat",chrome.cast.media.Ya);chrome.cast.media.bb={PAUSE:"pause",SEEK:"seek",STREAM_VOLUME:"stream_volume",STREAM_MUTE:"stream_mute"};
w("chrome.cast.media.MediaCommand",chrome.cast.media.bb);chrome.cast.media.hb={ALBUM:"ALBUM",PLAYLIST:"PLAYLIST",AUDIOBOOK:"AUDIOBOOK",RADIO_STATION:"RADIO_STATION",PODCAST_SERIES:"PODCAST_SERIES",TV_SERIES:"TV_SERIES",VIDEO_PLAYLIST:"VIDEO_PLAYLIST",LIVE_TV:"LIVE_TV",MOVIE:"MOVIE"};w("chrome.cast.media.QueueType",chrome.cast.media.hb);chrome.cast.media.V={GENERIC_CONTAINER:0,AUDIOBOOK_CONTAINER:1};w("chrome.cast.media.ContainerType",chrome.cast.media.V);
chrome.cast.media.G={GENERIC:0,MOVIE:1,TV_SHOW:2,MUSIC_TRACK:3,PHOTO:4,AUDIOBOOK_CHAPTER:5};w("chrome.cast.media.MetadataType",chrome.cast.media.G);chrome.cast.media.C={IDLE:"IDLE",PLAYING:"PLAYING",PAUSED:"PAUSED",BUFFERING:"BUFFERING"};w("chrome.cast.media.PlayerState",chrome.cast.media.C);chrome.cast.media.W={OFF:"REPEAT_OFF",ALL:"REPEAT_ALL",SINGLE:"REPEAT_SINGLE",ALL_AND_SHUFFLE:"REPEAT_ALL_AND_SHUFFLE"};w("chrome.cast.media.RepeatMode",chrome.cast.media.W);
chrome.cast.media.mb={PLAYBACK_START:"PLAYBACK_START",PLAYBACK_PAUSE:"PLAYBACK_PAUSE"};w("chrome.cast.media.ResumeState",chrome.cast.media.mb);chrome.cast.media.Aa={BUFFERED:"BUFFERED",LIVE:"LIVE",OTHER:"OTHER"};w("chrome.cast.media.StreamType",chrome.cast.media.Aa);chrome.cast.media.Za={CANCELLED:"CANCELLED",INTERRUPTED:"INTERRUPTED",FINISHED:"FINISHED",ERROR:"ERROR"};w("chrome.cast.media.IdleReason",chrome.cast.media.Za);chrome.cast.media.zb={TEXT:"TEXT",AUDIO:"AUDIO",VIDEO:"VIDEO"};
w("chrome.cast.media.TrackType",chrome.cast.media.zb);chrome.cast.media.wb={SUBTITLES:"SUBTITLES",CAPTIONS:"CAPTIONS",DESCRIPTIONS:"DESCRIPTIONS",CHAPTERS:"CHAPTERS",METADATA:"METADATA"};w("chrome.cast.media.TextTrackType",chrome.cast.media.wb);chrome.cast.media.rb={NONE:"NONE",OUTLINE:"OUTLINE",DROP_SHADOW:"DROP_SHADOW",RAISED:"RAISED",DEPRESSED:"DEPRESSED"};w("chrome.cast.media.TextTrackEdgeType",chrome.cast.media.rb);chrome.cast.media.xb={NONE:"NONE",NORMAL:"NORMAL",ROUNDED_CORNERS:"ROUNDED_CORNERS"};
w("chrome.cast.media.TextTrackWindowType",chrome.cast.media.xb);chrome.cast.media.sb={SANS_SERIF:"SANS_SERIF",MONOSPACED_SANS_SERIF:"MONOSPACED_SANS_SERIF",SERIF:"SERIF",MONOSPACED_SERIF:"MONOSPACED_SERIF",CASUAL:"CASUAL",CURSIVE:"CURSIVE",SMALL_CAPITALS:"SMALL_CAPITALS"};w("chrome.cast.media.TextTrackFontGenericFamily",chrome.cast.media.sb);chrome.cast.media.tb={NORMAL:"NORMAL",BOLD:"BOLD",BOLD_ITALIC:"BOLD_ITALIC",ITALIC:"ITALIC"};w("chrome.cast.media.TextTrackFontStyle",chrome.cast.media.tb);
chrome.cast.media.Ab={LIKE:"LIKE",DISLIKE:"DISLIKE",FOLLOW:"FOLLOW",UNFOLLOW:"UNFOLLOW"};w("chrome.cast.media.UserAction",chrome.cast.media.Ab);chrome.cast.media.ma=function(){this.customData=null};w("chrome.cast.media.GetStatusRequest",chrome.cast.media.ma);chrome.cast.media.qa=function(){this.customData=null};w("chrome.cast.media.PauseRequest",chrome.cast.media.qa);chrome.cast.media.sa=function(){this.customData=null};w("chrome.cast.media.PlayRequest",chrome.cast.media.sa);chrome.cast.media.nb=function(){this.customData=this.resumeState=this.currentTime=null};w("chrome.cast.media.SeekRequest",chrome.cast.media.nb);
chrome.cast.media.za=function(){this.customData=null};w("chrome.cast.media.StopRequest",chrome.cast.media.za);chrome.cast.media.Fb=function(a){this.volume=a;this.customData=null};w("chrome.cast.media.VolumeRequest",chrome.cast.media.Fb);
chrome.cast.media.ab=function(a){this.type="LOAD";this.requestId=0;this.sessionId=null;this.media=a;this.activeTrackIds=null;this.autoplay=!0;this.atvCredentialsType=this.atvCredentials=this.credentialsType=this.credentials=void 0;this.customData=this.currentTime=null;this.queueData=this.playbackRate=void 0};w("chrome.cast.media.LoadRequest",chrome.cast.media.ab);chrome.cast.media.Ua=function(a,b){this.requestId=0;this.activeTrackIds=a||null;this.textTrackStyle=b||null};
w("chrome.cast.media.EditTracksInfoRequest",chrome.cast.media.Ua);chrome.cast.media.U=function(a){this.containerType=a=a===void 0?chrome.cast.media.V.GENERIC_CONTAINER:a;this.containerDuration=this.containerImages=this.sections=this.title=void 0};w("chrome.cast.media.ContainerMetadata",chrome.cast.media.U);
chrome.cast.media.MediaMetadata=function(a){this.metadataType=this.type=a;this.queueItemId=this.sectionStartTimeInContainer=this.sectionStartAbsoluteTime=this.sectionStartTimeInMedia=this.sectionDuration=void 0};w("chrome.cast.media.MediaMetadata",chrome.cast.media.MediaMetadata);chrome.cast.media.la=function(){chrome.cast.media.MediaMetadata.call(this,chrome.cast.media.G.GENERIC);this.releaseDate=this.releaseYear=this.images=this.subtitle=this.title=void 0};n(chrome.cast.media.la,chrome.cast.media.MediaMetadata);
w("chrome.cast.media.GenericMediaMetadata",chrome.cast.media.la);chrome.cast.media.oa=function(){chrome.cast.media.MediaMetadata.call(this,chrome.cast.media.G.MOVIE);this.releaseDate=this.releaseYear=this.images=this.subtitle=this.studio=this.title=void 0};n(chrome.cast.media.oa,chrome.cast.media.MediaMetadata);w("chrome.cast.media.MovieMediaMetadata",chrome.cast.media.oa);
chrome.cast.media.Ca=function(){chrome.cast.media.MediaMetadata.call(this,chrome.cast.media.G.TV_SHOW);this.originalAirdate=this.releaseYear=this.images=this.episode=this.episodeNumber=this.season=this.seasonNumber=this.episodeTitle=this.title=this.seriesTitle=void 0};n(chrome.cast.media.Ca,chrome.cast.media.MediaMetadata);w("chrome.cast.media.TvShowMediaMetadata",chrome.cast.media.Ca);
chrome.cast.media.pa=function(){chrome.cast.media.MediaMetadata.call(this,chrome.cast.media.G.MUSIC_TRACK);this.releaseDate=this.releaseYear=this.images=this.discNumber=this.trackNumber=this.artistName=this.songName=this.composer=this.artist=this.albumArtist=this.title=this.albumName=void 0};n(chrome.cast.media.pa,chrome.cast.media.MediaMetadata);w("chrome.cast.media.MusicTrackMediaMetadata",chrome.cast.media.pa);
chrome.cast.media.ra=function(){chrome.cast.media.MediaMetadata.call(this,chrome.cast.media.G.PHOTO);this.creationDateTime=this.height=this.width=this.longitude=this.latitude=this.images=this.location=this.artist=this.title=void 0};n(chrome.cast.media.ra,chrome.cast.media.MediaMetadata);w("chrome.cast.media.PhotoMediaMetadata",chrome.cast.media.ra);
chrome.cast.media.ha=function(){chrome.cast.media.U.call(this,chrome.cast.media.V.AUDIOBOOK_CONTAINER);this.releaseDate=this.publisher=this.narrators=this.authors=void 0};n(chrome.cast.media.ha,chrome.cast.media.U);w("chrome.cast.media.AudiobookContainerMetadata",chrome.cast.media.ha);chrome.cast.media.ga=function(){chrome.cast.media.MediaMetadata.call(this,chrome.cast.media.G.AUDIOBOOK_CHAPTER);this.images=this.subtitle=this.bookTitle=this.chapterNumber=this.title=this.chapterTitle=void 0};
n(chrome.cast.media.ga,chrome.cast.media.MediaMetadata);w("chrome.cast.media.AudiobookChapterMediaMetadata",chrome.cast.media.ga);
chrome.cast.media.cb=function(a,b){this.contentId=a;this.contentUrl=void 0;this.streamType=chrome.cast.media.Aa.BUFFERED;this.contentType=b===void 0?"":b;this.metadata=null;this.atvEntity=this.entity=void 0;this.duration=null;this.startAbsoluteTime=void 0;this.customData=this.textTrackStyle=this.tracks=null;this.userActionStates=this.hlsVideoSegmentFormat=this.hlsSegmentFormat=this.vmapAdsRequest=this.breakClips=this.breaks=void 0};w("chrome.cast.media.MediaInfo",chrome.cast.media.cb);
chrome.cast.media.ua=function(a){this.itemId=null;this.media=a;this.autoplay=!0;this.startTime=0;this.playbackDuration=null;this.preloadTime=0;this.customData=this.activeTrackIds=null};w("chrome.cast.media.QueueItem",chrome.cast.media.ua);chrome.cast.media.Pa="CC1AD845";w("chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID",chrome.cast.media.Pa);chrome.cast.media.timeout={};chrome.cast.media.timeout.load=0;w("chrome.cast.media.timeout.load",chrome.cast.media.timeout.load);
chrome.cast.media.timeout.R=0;w("chrome.cast.media.timeout.getStatus",chrome.cast.media.timeout.R);chrome.cast.media.timeout.play=0;w("chrome.cast.media.timeout.play",chrome.cast.media.timeout.play);chrome.cast.media.timeout.pause=0;w("chrome.cast.media.timeout.pause",chrome.cast.media.timeout.pause);chrome.cast.media.timeout.seek=0;w("chrome.cast.media.timeout.seek",chrome.cast.media.timeout.seek);chrome.cast.media.timeout.stop=0;w("chrome.cast.media.timeout.stop",chrome.cast.media.timeout.stop);
chrome.cast.media.timeout.S=0;w("chrome.cast.media.timeout.setVolume",chrome.cast.media.timeout.S);chrome.cast.media.timeout.P=0;w("chrome.cast.media.timeout.editTracksInfo",chrome.cast.media.timeout.P);chrome.cast.media.timeout.A=0;w("chrome.cast.media.timeout.queue",chrome.cast.media.timeout.A);chrome.cast.media.yb=function(a,b){this.trackId=a;this.trackContentType=this.trackContentId=null;this.type=b;this.customData=this.subtype=this.language=this.name=null};w("chrome.cast.media.Track",chrome.cast.media.yb);
chrome.cast.media.ub=function(){this.customData=this.fontStyle=this.fontGenericFamily=this.fontFamily=this.fontScale=this.windowRoundedCornerRadius=this.windowColor=this.windowType=this.edgeColor=this.edgeType=this.backgroundColor=this.foregroundColor=null};w("chrome.cast.media.TextTrackStyle",chrome.cast.media.ub);chrome.cast.media.gb=function(a){this.type="QUEUE_LOAD";this.sessionId=this.requestId=null;this.items=a;this.startIndex=0;this.repeatMode=chrome.cast.media.W.OFF;this.customData=null};
w("chrome.cast.media.QueueLoadRequest",chrome.cast.media.gb);chrome.cast.media.ta=function(a){this.type="QUEUE_INSERT";this.sessionId=this.requestId=null;this.items=a;this.customData=this.insertBefore=null};w("chrome.cast.media.QueueInsertItemsRequest",chrome.cast.media.ta);chrome.cast.media.ib=function(a){this.type="QUEUE_UPDATE";this.sessionId=this.requestId=null;this.items=a;this.customData=null};w("chrome.cast.media.QueueUpdateItemsRequest",chrome.cast.media.ib);
chrome.cast.media.N=function(){this.type="QUEUE_UPDATE";this.customData=this.jump=this.currentItemId=this.sessionId=this.requestId=null};w("chrome.cast.media.QueueJumpRequest",chrome.cast.media.N);chrome.cast.media.xa=function(){this.type="QUEUE_UPDATE";this.customData=this.repeatMode=this.sessionId=this.requestId=null};w("chrome.cast.media.QueueSetPropertiesRequest",chrome.cast.media.xa);
chrome.cast.media.va=function(a){this.type="QUEUE_REMOVE";this.sessionId=this.requestId=null;this.itemIds=a;this.customData=null};w("chrome.cast.media.QueueRemoveItemsRequest",chrome.cast.media.va);chrome.cast.media.wa=function(a){this.type="QUEUE_REORDER";this.sessionId=this.requestId=null;this.itemIds=a;this.customData=this.insertBefore=null};w("chrome.cast.media.QueueReorderItemsRequest",chrome.cast.media.wa);
chrome.cast.media.Ka=function(a,b,c){this.id=a;this.breakClipIds=b;this.position=c;this.duration=void 0;this.isWatched=!1;this.isEmbedded=void 0};w("chrome.cast.media.Break",chrome.cast.media.Ka);chrome.cast.media.La=function(a){this.id=a;this.vastAdsRequest=this.customData=this.hlsSegmentFormat=this.clickThroughUrl=this.posterUrl=this.whenSkippable=this.duration=this.title=this.contentType=this.contentUrl=this.contentId=void 0};w("chrome.cast.media.BreakClip",chrome.cast.media.La);
chrome.cast.media.Cb=function(){this.adsResponse=this.adTagUrl=void 0};w("chrome.cast.media.VastAdsRequest",chrome.cast.media.Cb);chrome.cast.media.Ma=function(){this.whenSkippable=this.breakClipId=this.breakId=this.currentBreakClipTime=this.currentBreakTime=void 0};w("chrome.cast.media.BreakStatus",chrome.cast.media.Ma);chrome.cast.media.na=function(a,b,c,d){this.start=a;this.end=b;this.isMovingWindow=c;this.isLiveDone=d};w("chrome.cast.media.LiveSeekableRange",chrome.cast.media.na);
chrome.cast.media.fb=function(a,b,c,d,e,h,l){this.id=a;this.queueType=this.entity=void 0;this.name=b;this.description=c;this.repeatMode=d;this.shuffle=!1;this.items=e;this.startIndex=h;this.startTime=l;this.containerMetadata=void 0};w("chrome.cast.media.QueueData",chrome.cast.media.fb);chrome.cast.media.Bb=function(a){this.userAction=a;this.customData=void 0};w("chrome.cast.media.UserActionState",chrome.cast.media.Bb);chrome.cast.media.Db=function(a,b,c){this.width=a;this.height=b;this.hdrType=c};
w("chrome.cast.media.VideoInformation",chrome.cast.media.Db);var A=null;chrome.cast.media.i=function(a,b){this.sessionId=a;this.mediaSessionId=b;this.media=null;this.videoInfo=this.queueData=void 0;this.playbackRate=1;this.playerState=chrome.cast.media.C.IDLE;this.currentTime=0;this.h=-1;this.supportedMediaCommands=[];this.volume=new chrome.cast.Volume;this.items=this.preloadedItemId=this.loadingItemId=this.currentItemId=this.customData=this.activeTrackIds=this.idleReason=null;this.repeatMode=chrome.cast.media.W.OFF;this.breakStatus=void 0;this.m=!1;this.j=[];this.liveSeekableRange=
void 0};f=chrome.cast.media.i.prototype;f.R=function(a,b,c){a||(a=new chrome.cast.media.ma);A.o(this,"MEDIA_GET_STATUS",a,b,c,chrome.cast.media.timeout.R)};f.play=function(a,b,c){var d=A;a||(a=new chrome.cast.media.sa);d.o(this,"PLAY",a,b,c,chrome.cast.media.timeout.play)};f.pause=function(a,b,c){var d=A;a||(a=new chrome.cast.media.qa);d.o(this,"PAUSE",a,b,c,chrome.cast.media.timeout.pause)};f.seek=function(a,b,c){A.o(this,"SEEK",a,b,c,chrome.cast.media.timeout.seek)};
f.stop=function(a,b,c){a||(a=new chrome.cast.media.za);A.o(this,"STOP_MEDIA",a,b,c,chrome.cast.media.timeout.stop)};f.S=function(a,b,c){A.o(this,"MEDIA_SET_VOLUME",a,b,c,chrome.cast.media.timeout.S)};f.P=function(a,b,c){A.o(this,"EDIT_TRACKS_INFO",a,b,c,chrome.cast.media.timeout.P)};f.Ub=function(a,b,c){A.o(this,"QUEUE_INSERT",a,b,c,chrome.cast.media.timeout.A)};f.Tb=function(a,b,c){A.o(this,"QUEUE_INSERT",new chrome.cast.media.ta([a]),b,c,chrome.cast.media.timeout.A)};
f.ec=function(a,b,c){A.o(this,"QUEUE_UPDATE",a,b,c,chrome.cast.media.timeout.A)};f.Zb=function(a,b){var c=new chrome.cast.media.N;c.jump=-1;A.o(this,"QUEUE_UPDATE",c,a,b,chrome.cast.media.timeout.A)};f.Yb=function(a,b){var c=new chrome.cast.media.N;c.jump=1;A.o(this,"QUEUE_UPDATE",c,a,b,chrome.cast.media.timeout.A)};f.Vb=function(a,b,c){if(!(B(this,a)<0)){var d=new chrome.cast.media.N;d.currentItemId=a;A.o(this,"QUEUE_UPDATE",d,b,c,chrome.cast.media.timeout.A)}};
f.dc=function(a,b,c){var d=new chrome.cast.media.xa;d.repeatMode=a;A.o(this,"QUEUE_UPDATE",d,b,c,chrome.cast.media.timeout.A)};f.bc=function(a,b,c){A.o(this,"QUEUE_REMOVE",a,b,c,chrome.cast.media.timeout.A)};f.ac=function(a,b,c){B(this,a)<0||A.o(this,"QUEUE_REMOVE",new chrome.cast.media.va([a]),b,c,chrome.cast.media.timeout.A)};f.cc=function(a,b,c){A.o(this,"QUEUE_REORDER",a,b,c,chrome.cast.media.timeout.A)};
f.Xb=function(a,b,c,d){var e=B(this,a);if(!(e<0))if(b<0)d&&d(new chrome.cast.Error(chrome.cast.B.INVALID_PARAMETER));else if(e==b)c&&c();else{var h=null;b=b>e?b+1:b;b<this.items.length&&(h=this.items[b]);a=new chrome.cast.media.wa([a]);a.insertBefore=h?h.itemId:null;A.o(this,"QUEUE_REORDER",a,c,d,chrome.cast.media.timeout.A)}};f.rc=function(a){return this.supportedMediaCommands.indexOf(a)>-1};
f.Ob=function(){if(this.playerState==chrome.cast.media.C.PLAYING&&this.h>=0){var a=this.currentTime+(Date.now()-this.h)/1E3*this.playbackRate;this.media&&this.media.duration!=null&&a>this.media.duration&&this.media.duration!=-1&&(a=this.media.duration);a<0&&(a=0);return a}return this.currentTime};f.Mb=function(){if(this.breakStatus&&this.breakStatus.currentBreakTime!==void 0)return this.playerState==chrome.cast.media.C.PLAYING&&this.h>=0?this.breakStatus.currentBreakTime+(Date.now()-this.h)/1E3:this.breakStatus.currentBreakTime};
f.Lb=function(){if(this.breakStatus&&this.breakStatus.currentBreakClipTime!==void 0)return this.playerState==chrome.cast.media.C.PLAYING&&this.h>=0?this.breakStatus.currentBreakClipTime+(Date.now()-this.h)/1E3:this.breakStatus.currentBreakClipTime};
f.Nb=function(){if(this.liveSeekableRange&&this.liveSeekableRange.start!==void 0&&this.liveSeekableRange.end!==void 0){if(this.playerState==chrome.cast.media.C.PLAYING&&this.h>=0){var a=(Date.now()-this.h)/1E3,b=new chrome.cast.media.na;b.isMovingWindow=this.liveSeekableRange.isMovingWindow;b.isLiveDone=this.liveSeekableRange.isLiveDone;b.start=b.isMovingWindow?this.liveSeekableRange.start+a:this.liveSeekableRange.start;b.end=b.isLiveDone?this.liveSeekableRange.end:this.liveSeekableRange.end+a;return b}return this.liveSeekableRange}};
f.Z=function(a){A.Hb(this,a)};f.ca=function(a){A.hc(this,a)};var B=function(a,b){return ya(a.items,function(c){return c.itemId==b})};w("chrome.cast.media.Media",chrome.cast.media.i);chrome.cast.media.i.prototype.removeUpdateListener=chrome.cast.media.i.prototype.ca;chrome.cast.media.i.prototype.addUpdateListener=chrome.cast.media.i.prototype.Z;chrome.cast.media.i.prototype.getEstimatedLiveSeekableRange=chrome.cast.media.i.prototype.Nb;chrome.cast.media.i.prototype.getEstimatedBreakClipTime=chrome.cast.media.i.prototype.Lb;
chrome.cast.media.i.prototype.getEstimatedBreakTime=chrome.cast.media.i.prototype.Mb;chrome.cast.media.i.prototype.getEstimatedTime=chrome.cast.media.i.prototype.Ob;chrome.cast.media.i.prototype.supportsCommand=chrome.cast.media.i.prototype.rc;chrome.cast.media.i.prototype.queueMoveItemToNewIndex=chrome.cast.media.i.prototype.Xb;chrome.cast.media.i.prototype.queueReorderItems=chrome.cast.media.i.prototype.cc;chrome.cast.media.i.prototype.queueRemoveItem=chrome.cast.media.i.prototype.ac;
chrome.cast.media.i.prototype.queueRemoveItems=chrome.cast.media.i.prototype.bc;chrome.cast.media.i.prototype.queueSetRepeatMode=chrome.cast.media.i.prototype.dc;chrome.cast.media.i.prototype.queueJumpToItem=chrome.cast.media.i.prototype.Vb;chrome.cast.media.i.prototype.queueNext=chrome.cast.media.i.prototype.Yb;chrome.cast.media.i.prototype.queuePrev=chrome.cast.media.i.prototype.Zb;chrome.cast.media.i.prototype.queueUpdateItems=chrome.cast.media.i.prototype.ec;
chrome.cast.media.i.prototype.queueAppendItem=chrome.cast.media.i.prototype.Tb;chrome.cast.media.i.prototype.queueInsertItems=chrome.cast.media.i.prototype.Ub;chrome.cast.media.i.prototype.editTracksInfo=chrome.cast.media.i.prototype.P;chrome.cast.media.i.prototype.setVolume=chrome.cast.media.i.prototype.S;chrome.cast.media.i.prototype.stop=chrome.cast.media.i.prototype.stop;chrome.cast.media.i.prototype.seek=chrome.cast.media.i.prototype.seek;chrome.cast.media.i.prototype.pause=chrome.cast.media.i.prototype.pause;
chrome.cast.media.i.prototype.play=chrome.cast.media.i.prototype.play;chrome.cast.media.i.prototype.getStatus=chrome.cast.media.i.prototype.R;var Da=function(a,b,c){this.sessionId=a;this.namespaceName=b;this.message=c};var Ea=function(a,b){this.type="SET_VOLUME";this.requestId=0;this.volume=a;this.expectedVolume=b||null};var Fa=function(a){this.type="STOP";this.requestId=0;this.sessionId=a||null};chrome.cast.l=function(a,b,c,d,e){this.sessionId=a;this.appId=b;this.displayName=c;this.statusText=null;this.appImages=d;this.receiver=e;this.senderApps=[];this.namespaces=[];this.media=[];this.status=chrome.cast.L.CONNECTED;this.transportId=""};f=chrome.cast.l.prototype;f.qc=function(a,b,c){var d=A;a=new Ea(new chrome.cast.Volume(a,null),this.receiver.volume);d.setReceiverVolume(this.sessionId,a,b,c)};
f.oc=function(a,b,c){a=new Ea(new chrome.cast.Volume(null,a),this.receiver.volume);A.setReceiverVolume(this.sessionId,a,b,c)};f.getDialAppInfo=function(a,b){A.getDialAppInfo(a,b)};f.Pb=function(a,b){A.leaveSession(this.sessionId,a,b)};f.stop=function(a,b){A.Ea(new Fa(this.sessionId),a,b,chrome.cast.timeout.stopSession)};f.sendMessage=function(a,b,c,d){A.lc(new Da(this.sessionId,a,b),c,d)};f.Z=function(a){A.Jb(this.sessionId,a)};f.ca=function(a){A.kc(this.sessionId,a)};
f.Ib=function(a,b){A.Gb(this.sessionId,a,b)};f.X=function(a){A.X(this.sessionId,a)};f.aa=function(a){A.aa(this.sessionId,a)};f.jc=function(a,b){A.fc(this.sessionId,a,b)};f.Qb=function(a,b,c){a.sessionId=this.sessionId;A.Fa(a,"LOAD",b,c)};f.Wb=function(a,b,c){a.sessionId=this.sessionId;A.Fa(a,"QUEUE_LOAD",b,c)};w("chrome.cast.Session",chrome.cast.l);chrome.cast.l.prototype.queueLoad=chrome.cast.l.prototype.Wb;chrome.cast.l.prototype.loadMedia=chrome.cast.l.prototype.Qb;
chrome.cast.l.prototype.removeMessageListener=chrome.cast.l.prototype.jc;chrome.cast.l.prototype.removeMediaListener=chrome.cast.l.prototype.aa;chrome.cast.l.prototype.addMediaListener=chrome.cast.l.prototype.X;chrome.cast.l.prototype.addMessageListener=chrome.cast.l.prototype.Ib;chrome.cast.l.prototype.removeUpdateListener=chrome.cast.l.prototype.ca;chrome.cast.l.prototype.addUpdateListener=chrome.cast.l.prototype.Z;chrome.cast.l.prototype.sendMessage=chrome.cast.l.prototype.sendMessage;
chrome.cast.l.prototype.stop=chrome.cast.l.prototype.stop;chrome.cast.l.prototype.leave=chrome.cast.l.prototype.Pb;chrome.cast.l.prototype.getDialAppInfo=chrome.cast.l.prototype.getDialAppInfo;chrome.cast.l.prototype.setReceiverMuted=chrome.cast.l.prototype.oc;chrome.cast.l.prototype.setReceiverVolumeLevel=chrome.cast.l.prototype.qc;var C=function(a,b){this.h=a[q.Symbol.iterator]();this.j=b};C.prototype[Symbol.iterator]=function(){return this};C.prototype.next=function(){var a=this.h.next();return{value:a.done?void 0:this.j.call(void 0,a.value),done:a.done}};var Ga=function(a,b){return new C(a,b)};function D(){}D.prototype.next=function(){return E};var E=za({done:!0,value:void 0});D.prototype.u=function(){return this};function Ha(a){if(a instanceof D)return a;if(typeof a.u=="function")return a.u(!1);if(r(a)){var b=0,c=new D;c.next=function(){for(;;){if(b>=a.length)return E;if(b in a)return{value:a[b++],done:!1};b++}};return c}throw Error("Not implemented");}function F(a,b){if(r(a))xa(a,b);else for(a=Ha(a);;){var c=a.next();if(c.done)break;b.call(void 0,c.value,void 0,a)}};var Ia=function(a){if(a instanceof G||a instanceof H||a instanceof I)return a;if(typeof a.next=="function")return new G(function(){return a});if(typeof a[Symbol.iterator]=="function")return new G(function(){return a[Symbol.iterator]()});if(typeof a.u=="function")return new G(function(){return a.u()});throw Error("Not an iterator or iterable.");},G=function(a){this.h=a};G.prototype.u=function(){return new H(this.h())};G.prototype[Symbol.iterator]=function(){return new I(this.h())};G.prototype.j=function(){return new I(this.h())};
var H=function(a){this.h=a};n(H,D);H.prototype.next=function(){return this.h.next()};H.prototype[Symbol.iterator]=function(){return new I(this.h)};H.prototype.j=function(){return new I(this.h)};var I=function(a){G.call(this,function(){return a});this.m=a};n(I,G);I.prototype.next=function(){return this.m.next()};function J(a,b){this.j={};this.h=[];this.m=this.size=0;var c=arguments.length;if(c>1){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof J)for(c=Ja(a),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}J.prototype.M=function(){K(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.j[this.h[b]]);return a};var Ja=function(a){K(a);return a.h.concat()};
J.prototype.has=function(a){return L(this.j,a)};J.prototype.clear=function(){this.j={};this.m=this.size=this.h.length=0};J.prototype.remove=function(a){return this.delete(a)};J.prototype.delete=function(a){return L(this.j,a)?(delete this.j[a],--this.size,this.m++,this.h.length>2*this.size&&K(this),!0):!1};
var K=function(a){if(a.size!=a.h.length){for(var b=0,c=0;b<a.h.length;){var d=a.h[b];L(a.j,d)&&(a.h[c++]=d);b++}a.h.length=c}if(a.size!=a.h.length){b={};for(d=c=0;c<a.h.length;){var e=a.h[c];L(b,e)||(a.h[d++]=e,b[e]=1);c++}a.h.length=d}};f=J.prototype;f.get=function(a,b){return L(this.j,a)?this.j[a]:b};f.set=function(a,b){L(this.j,a)||(this.size+=1,this.h.push(a),this.m++);this.j[a]=b};f.forEach=function(a,b){for(var c=Ja(this),d=0;d<c.length;d++){var e=c[d],h=this.get(e);a.call(b,h,e,this)}};
f.keys=function(){return Ia(this.u(!0)).j()};f.values=function(){return Ia(this.u(!1)).j()};f.entries=function(){var a=this;return Ga(this.keys(),function(b){return[b,a.get(b)]})};f.u=function(a){K(this);var b=0,c=this.m,d=this,e=new D;e.next=function(){if(c!=d.m)throw Error("The map has changed since the iterator was created");if(b>=d.h.length)return E;var h=d.h[b++];return{value:a?h:d.j[h],done:!1}};return e};var L=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var M=function(a,b){this.requestId=a;this.v=b;this.Ha=null};M.prototype.j=function(){};var Ka=function(){this.h=new J},La=function(a,b){a.h.set(b.requestId,b);b.Ha=setTimeout(function(){a.h.delete(b.requestId);b.j()},b.v)},Ma=function(a,b){var c=a.h.get(b);if(!c)return null;clearTimeout(c.Ha);a.h.delete(b);return c};var N=function(a,b,c,d){M.call(this,a,d||6E5);this.m=b;this.h=c};n(N,M);N.prototype.j=function(){this.h(new chrome.cast.Error(chrome.cast.B.TIMEOUT))};var O=function(a,b,c,d){this.type=a;this.message=b;this.sequenceNumber=c!==void 0?c:-1;this.timeoutMillis=d||0;this.clientId=""};var P=function(a){this.m=a;this.j=String(Date.now())+String(Math.floor(Math.random()*1E5));this.h=null},Na=function(a,b){if(!a.h)return"No active session";b.clientId=a.j;b=JSON.stringify(b);if(b.length>32768)return"Message length over limit";a.h.send(b);return null};P.prototype.connect=function(a){this.h=a;this.h.onmessage=v(this.v,this);Na(this,new O("client_connect",this.j))};P.prototype.disconnect=function(){this.h.close();this.h=null};
P.prototype.v=function(a){a=JSON.parse(a.data);if(a.clientId==this.j)this.m.onMessage(a)};var Oa=function(a,b,c){this.m=a;this.j=b;this.h=c},Pa=function(a){var b="cast-dial:"+a.m,c=new URLSearchParams;a.j&&c.set("dialPostData",a.j);a.h&&c.set("clientId",a.h);(a=c.toString())&&(b+="?"+a);return b};var Qa=function(a,b,c,d,e,h,l,m,p,t){this.K=a;this.h=b||null;this.m=c||null;this.D=d||null;this.F=e!==void 0?e:null;this.j=h||null;this.J=l||null;this.H=m||!1;this.I=p?["WEB","ANDROID_TV"]:["WEB"];this.v=t||null},Ra=function(a){var b=a.K.map(function(c){var d="cast:"+c.appId,e=new URLSearchParams;c.capabilities&&c.capabilities.length>0&&e.set("capabilities",c.capabilities.join(","));a.h&&e.set("clientId",a.h);a.m&&e.set("autoJoinPolicy",a.m);a.D&&e.set("defaultActionPolicy",a.D);a.F!=null&&e.set("launchTimeout",
String(a.F));a.H&&e.set("invisibleSender","true");e.set("supportedAppTypes",a.I.join(","));c=e.set;var h=JSON,l=h.stringify,m={launchCheckerParams:{}};a.v&&(m.launchCheckerParams.credentialsData=a.v);c.call(e,"appParams",l.call(h,m));return d+"?"+e.toString()});a.j&&b.push(Pa(new Oa(a.j,a.J,a.h)));return b};var Sa=function(){this.h={};this.j={}},Ta=function(a,b,c){var d=a.h[b];return d?(d.status=c,d.media.forEach(function(e){delete a.j[e.sessionId+"#"+e.mediaSessionId]}),delete a.h[b],!0):!1},Va=function(a,b){var c=a.h[b.sessionId];if(c)return c.statusText=b.statusText,c.namespaces=b.namespaces||[],c.receiver.volume=b.receiver.volume,c;c=new chrome.cast.l(b.sessionId,b.appId,b.displayName,b.appImages,b.receiver);for(var d in b)d=="media"?c.media=b.media.map(function(e){e=Ua(a,e);e.v=!1;e.m=!0;return e}):
b.hasOwnProperty(d)&&(c[d]=b[d]);return a.h[b.sessionId]=c},Ua=function(a,b){var c=b.sessionId+"#"+b.mediaSessionId,d=a.j[c];d||(d=new chrome.cast.media.i(b.sessionId,b.mediaSessionId),a.j[c]=d,(a=a.h[b.sessionId])&&a.media.push(d));a=d;a.currentItemId=null;a.loadingItemId=null;a.preloadedItemId=null;for(var e in b)e!="items"&&b.hasOwnProperty(e)&&(e=="volume"?(a.volume.level=b.volume.level,a.volume.muted=b.volume.muted):a[e]=b[e]);e=fa(["idleReason","extendedStatus","breakStatus"]);for(c=e.next();!c.done;c=
e.next())c=c.value,b.hasOwnProperty(c)||(a[c]=null);"currentTime"in b&&(a.h=Date.now());if(a.playerState==chrome.cast.media.C.IDLE&&a.loadingItemId==null)a.currentItemId=null,a.loadingItemId=null,a.preloadedItemId=null,a.items=null;else if(b.hasOwnProperty("items")&&b.items){e=[];var h=a.items;c={};if(h)for(var l=0;l<h.length;l++)c[h[l].itemId]=l;b=fa(b.items);for(h=b.next();!h.done;h=b.next()){h=h.value;if(!h.media){l=h.itemId;var m=a.items?a.items[c[l]]:null;m&&m.media?h.media=m.media:l==a.currentItemId&&
a.media&&(h.media=a.media)}l=e;m=l.push;var p=void 0,t=new chrome.cast.media.ua(h.media);for(p in h)h.hasOwnProperty(p)&&(t[p]=h[p]);m.call(l,t)}a.items=e}return d},Wa=function(a,b){delete a.j[b.sessionId+"#"+b.mediaSessionId];if(a=a.h[b.sessionId])b=a.media.indexOf(b),b!=-1&&a.media.splice(b,1)};function Q(){var a=q.navigator;return a&&(a=a.userAgent)?a:""};var Xa=Q().toLowerCase().indexOf("webkit")!=-1&&Q().indexOf("Edge")==-1;var Ya={},R=null,Za=Q().indexOf("Gecko")!=-1&&!(Q().toLowerCase().indexOf("webkit")!=-1&&Q().indexOf("Edge")==-1)&&!(Q().indexOf("Trident")!=-1||Q().indexOf("MSIE")!=-1)&&Q().indexOf("Edge")==-1||Xa||typeof q.btoa=="function";
function $a(a){if(Za)var b=q.btoa(a);else{b=[];for(var c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);if(e>255)throw Error("go/unicode-to-byte-error");b[c++]=e}a=void 0;a===void 0&&(a=0);if(!R)for(R={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;e<5;e++){var h=c.concat(d[e].split(""));Ya[e]=h;for(var l=0;l<h.length;l++){var m=h[l];R[m]===void 0&&(R[m]=l)}}a=Ya[a];c=Array(Math.floor(b.length/3));d=a[64]||"";for(e=h=0;h<b.length-2;h+=
3){var p=b[h],t=b[h+1];m=b[h+2];l=a[p>>2];p=a[(p&3)<<4|t>>4];t=a[(t&15)<<2|m>>6];m=a[m&63];c[e++]=""+l+p+t+m}l=0;m=d;switch(b.length-h){case 2:l=b[h+1],m=a[(l&15)<<2]||d;case 1:b=b[h],c[e]=""+a[b>>2]+a[(b&3)<<4|l>>4]+m+d}b=c.join("")}return b};var ab=function(a){if(a.M&&typeof a.M=="function")return a.M();if(typeof Map!=="undefined"&&a instanceof Map||typeof Set!=="undefined"&&a instanceof Set)return Array.from(a.values());if(typeof a==="string")return a.split("");if(r(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};function S(){this.h=new J;this.size=0}var T=function(a){var b=typeof a;return b=="object"&&a||b=="function"?"o"+(Object.prototype.hasOwnProperty.call(a,u)&&a[u]||(a[u]=++ha)):b.slice(0,1)+a};f=S.prototype;f.add=function(a){this.h.set(T(a),a);this.size=this.h.size};f.removeAll=function(a){a=ab(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c]);this.size=this.h.size};f.delete=function(a){a=this.h.remove(T(a));this.size=this.h.size;return a};f.remove=function(a){return this.delete(a)};
f.clear=function(){this.h.clear();this.size=0};f.has=function(a){var b=this.h;a=T(a);return b.has(a)};f.contains=function(a){var b=this.h;a=T(a);return b.has(a)};f.M=function(){return this.h.M()};f.values=function(){return this.h.values()};f.u=function(){return this.h.u(!1)};S.prototype[Symbol.iterator]=function(){return this.values()};var U=function(){this.D=new P(this);this.h=null;this.I=new Sa;this.j=0;this.T=new Ka;this.F=new J;this.v=new J;this.K=new J;this.H=[];this.Va=this.Kb.bind(this);this.ja=this.J=this.m=null},bb=function(a){var b=new chrome.cast.Error(chrome.cast.B.INVALID_PARAMETER,"Already requesting session");a&&a(b)},V=function(a,b,c,d){c&&La(a.T,c);d!==void 0?b.sequenceNumber=d:(b.sequenceNumber=a.j,a.j=(a.j+1)%9007199254740992);d=Na(a.D,b);c&&d&&(a=Ma(a.T,b.sequenceNumber))&&(a=a.h,d=new chrome.cast.Error(chrome.cast.B.INVALID_PARAMETER,
d),a&&a(d))};
U.prototype.initialize=function(a,b){var c=this;A=this;this.h=a;a.invisibleSender||(a=new PresentationRequest(W(this)),a.getAvailability().then(function(d){d.onchange=function(){c.h.receiverListener(d.value?chrome.cast.O.AVAILABLE:chrome.cast.O.UNAVAILABLE)};d.onchange()},function(){c.h.receiverListener(chrome.cast.O.AVAILABLE)}),a.onconnectionavailable=function(d){X(c,d.connection)},this.ja=(q.navigator||null).presentation.defaultRequest=a,a.reconnect(chrome.cast.Ia).then(function(d){X(c,d)},function(){}));
b&&b(void 0)};U.prototype.ea=function(a){a.navigator.presentation.defaultRequest=this.ja};var X=function(a,b,c){c=c===void 0?null:c;b.onclose=function(d){a.m=null;switch(d.reason){case "closed":cb(a,chrome.cast.L.DISCONNECTED);break;case "error":if(c){d=c;var e=new chrome.cast.Error(chrome.cast.B.SESSION_ERROR);d&&d(e)}}};b.onterminate=function(){cb(a,chrome.cast.L.STOPPED)};b.state=="connected"?a.D.connect(b):b.onconnect=function(){a.D.connect(b)}};
U.prototype.requestSession=function(a,b,c){var d=this;this.m?bb(b):(c=W(this,c),this.m=a,(new PresentationRequest(c)).start().then(function(e){X(d,e,b)}).catch(function(e){d.m=null;e=new chrome.cast.Error(e.name=="AbortError"||e.name=="NotAllowedError"?chrome.cast.B.CANCEL:chrome.cast.B.SESSION_ERROR);b&&b(e)}))};
var W=function(a,b){var c=null,d=null;b=b||a.h.sessionRequest;var e=b.dialRequest;e&&(c=e.appName,(d=e.launchParameter)&&!d.match(db)&&(d=$a(d)));var h=[];h.push({appId:b.appId,capabilities:b.capabilities});b||xa(a.h.additionalSessionRequests,function(l){h.push({appId:l.appId,capabilities:l.capabilities})});return Ra(new Qa(h,a.D.j,a.h.autoJoinPolicy,a.h.defaultActionPolicy,b.requestSessionTimeout,c,d,a.h.invisibleSender,b.androidReceiverCompatible,b.credentialsData))};
U.prototype.Fa=function(a,b,c,d){eb(this,null,b,a,function(e){e.m=!0;c&&c(e)},function(e){d(e)},chrome.cast.media.timeout.load)};U.prototype.o=function(a,b,c,d,e,h){var l=this;eb(this,a,b,c,function(m){l.Da(m);d&&d(void 0)},e,h)};var eb=function(a,b,c,d,e,h,l){d.type=c;b!=null&&(d.mediaSessionId=b.mediaSessionId,d.sessionId=b.sessionId);a.Ea(d,function(m){m.status&&m.status.length==1?e&&e(m.status[0]):(m=new chrome.cast.Error(chrome.cast.B.SESSION_ERROR),h&&h(m))},h,l)};f=U.prototype;
f.setReceiverVolume=function(a,b,c,d){b.sessionId=a;V(this,new O("v2_message",b,void 0,chrome.cast.timeout.setReceiverVolume),new N(this.j,c,d,chrome.cast.timeout.sendCustomMessage))};f.getDialAppInfo=function(a,b){V(this,new O("dial_app_info",void 0,void 0,chrome.cast.timeout.getDialAppInfo),new N(this.j,a,b,chrome.cast.timeout.sendCustomMessage))};f.da=function(a){var b=this;(new PresentationRequest(W(this))).reconnect(chrome.cast.eb+a).then(function(c){X(b,c)},function(){})};
f.leaveSession=function(a,b,c){V(this,new O("leave_session",a,void 0,chrome.cast.timeout.leaveSession),new N(this.j,b,c,chrome.cast.timeout.leaveSession))};f.lc=function(a,b,c){V(this,new O("app_message",a,void 0,chrome.cast.timeout.sendCustomMessage),new N(this.j,b,c,chrome.cast.timeout.sendCustomMessage))};f.Ea=function(a,b,c,d){V(this,new O("v2_message",a,void 0,d),new N(this.j,b,c,d))};var fb=function(a,b,c){var d=a.get(b);d||(d=new S,a.set(b,d));d.add(c)};f=U.prototype;
f.Jb=function(a,b){fb(this.F,a,b)};f.kc=function(a,b){(a=this.F.get(a))&&a.remove(b)};f.Y=function(a){this.H.push(a)};f.ba=function(a){a=this.H.indexOf(a);a>=0&&this.H.splice(a,1)};f.Gb=function(a,b,c){var d=this.v.get(a);d||(d=new J,this.v.set(a,d));a=d.get(b);a||(a=new S,d.set(b,a));a.add(c)};f.fc=function(a,b,c){(a=this.v.get(a))&&(b=a.get(b))&&b.remove(c)};f.X=function(a,b){fb(this.K,a,b)};f.aa=function(a,b){(a=this.K.get(a))&&a.remove(b)};f.Hb=function(a,b){a.j.indexOf(b)==-1&&a.j.push(b)};
f.hc=function(a,b){b=a.j.indexOf(b);b!=-1&&a.j.splice(b,1)};f.Da=function(a){if(a.m){var b=a.playerState!=chrome.cast.media.C.IDLE||a.loadingItemId!=null;a.j.forEach(function(d){d(b)});b||Wa(this.I,a)}else{a.m=!0;var c=this.K.get(a.sessionId);c&&F(c.u(),function(d){d(a)})}};f.Kb=function(a){return Ua(this.I,a)};var cb=function(a,b){if(a.J){var c=a.J;a.J=null;a.D.disconnect();var d=b!=chrome.cast.L.STOPPED;Ta(a.I,c,b)&&(a.v.delete(c),a.K.delete(c),b=a.F.get(c))&&(a.F.delete(c),F(b.u(),function(e){e(d)}))}};
U.prototype.onMessage=function(a){switch(a.type){case "new_session":case "update_session":a.message=Va(this.I,a.message);break;case "v2_message":var b=a.message;b&&b.type=="MEDIA_STATUS"&&b.status&&(b.status=b.status.map(this.Va))}if(b=Ma(this.T,a.sequenceNumber))a.type=="error"?(b=b.h)&&b(a.message):(b=b.m)&&b(a.message);if(b=a.message)switch(a.type){case "receiver_action":gb(this,b);break;case "new_session":this.J=b.sessionId;this.m?(this.m(b),this.m=null):this.h&&this.h.sessionListener(b);break;
case "update_session":hb(this,b);break;case "app_message":ib(this,b);break;case "v2_message":b.type=="MEDIA_STATUS"&&b.status.forEach(this.Da.bind(this));break;case "custom_dial_launch":jb(this,a.sequenceNumber,b)}};
var hb=function(a,b){(a=a.F.get(b.sessionId))&&F(a.u(),function(c){c(!0)})},gb=function(a,b){a.H.forEach(function(c){c(b.receiver,b.action)})},ib=function(a,b){(a=a.v.get(b.sessionId))&&(a=a.get(b.namespaceName))&&F(a.u(),function(c){c(b.namespaceName,b.message)})},Y=function(a,b,c){V(a,new O("custom_dial_launch",c,void 0,chrome.cast.timeout.sendCustomMessage),null,b)},jb=function(a,b,c){a.h.customDialLaunchCallback?a.h.customDialLaunchCallback(c).then(function(d){Y(a,b,d)},function(){Y(a,b)}):Y(a,
b)},db=RegExp("^([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?$"),Z=new U;chrome.cast.initialize=function(a,b,c){Z.initialize(a,b,c)};w("chrome.cast.initialize",chrome.cast.initialize);chrome.cast.ea=function(a){Z.ea(a)};w("chrome.cast.setPageContext",chrome.cast.ea);chrome.cast.requestSession=function(a,b,c){Z.requestSession(a,b,c)};w("chrome.cast.requestSession",chrome.cast.requestSession);chrome.cast.Sb=function(){};w("chrome.cast.precache",chrome.cast.Sb);chrome.cast.da=function(a){Z.da(a)};w("chrome.cast.requestSessionById",chrome.cast.da);chrome.cast.Y=function(a){Z.Y(a)};
w("chrome.cast.addReceiverActionListener",chrome.cast.Y);chrome.cast.ba=function(a){Z.ba(a)};w("chrome.cast.removeReceiverActionListener",chrome.cast.ba);chrome.cast.Rb=function(){};w("chrome.cast.logMessage",chrome.cast.Rb);chrome.cast.mc=function(a,b){b()};w("chrome.cast.setCustomReceivers",chrome.cast.mc);chrome.cast.nc=function(a,b){b()};w("chrome.cast.setReceiverDisplayStatus",chrome.cast.nc);chrome.cast.unescape=function(a){return a.indexOf("&")!=-1?"document"in q?Ba(a):Ca(a):a};
w("chrome.cast.unescape",chrome.cast.unescape);chrome.cast.isAvailable=!1;w("chrome.cast.isAvailable",chrome.cast.isAvailable);chrome.cast.Ga=!1;chrome.cast.fa=function(){if(!chrome.cast.Ga){chrome.cast.Ga=!0;chrome.cast.isAvailable=!0;var a=window.__onGCastApiAvailable;a&&typeof a=="function"&&a(!0)}};document.readyState=="complete"?chrome.cast.fa():(window.addEventListener("load",chrome.cast.fa,!1),window.addEventListener("DOMContentLoaded",chrome.cast.fa,!1));}).call(this);
